from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.skill_list, name='skill-list'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.skill_details, name='skill-details'),
    url(r'^(?P<pk>[0-9]+)/publish/$',
        views.skill_toggle_is_published, name='skill-publish'),
    url(r'^add/select-type/$',
        views.skill_select_type, name='skill-add-select-type'),
    url(r'^add/(?P<type_pk>[0-9]+)/$',
        views.skill_create, name='skill-add'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.skill_edit, name='skill-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.skill_delete, name='skill-delete'),
    url(r'^bulk-update/$',
        views.skill_bulk_update, name='skill-bulk-update'),
    url(r'^ajax/skills/$',
        views.ajax_skills_list, name='ajax-skills'),

    url(r'^types/$',
        views.skill_type_list, name='skill-type-list'),
    url(r'^types/add/$',
        views.skill_type_create, name='skill-type-add'),
    url(r'^types/(?P<pk>[0-9]+)/update/$',
        views.skill_type_edit, name='skill-type-update'),
    url(r'^types/(?P<pk>[0-9]+)/delete/$',
        views.skill_type_delete, name='skill-type-delete'),

    url(r'^(?P<skill_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_details, name='variant-details'),
    url(r'^(?P<skill_pk>[0-9]+)/variants/add/$',
        views.variant_create, name='variant-add'),
    url(r'^(?P<skill_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/update/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<skill_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<skill_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/images/$',
        views.variant_images, name='variant-images'),
    url(r'^ajax/variants/$',
        views.ajax_available_variants_list, name='ajax-available-variants'),

    url(r'^(?P<skill_pk>[0-9]+)/images/$',
        views.skill_images, name='skill-image-list'),
    url(r'^(?P<skill_pk>[0-9]+)/images/add/$',
        views.skill_image_create, name='skill-image-add'),
    url(r'^(?P<skill_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.skill_image_edit, name='skill-image-update'),
    url(r'^(?P<skill_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.skill_image_delete, name='skill-image-delete'),
    url(r'^(?P<skill_pk>[0-9]+)/images/reorder/$',
        views.ajax_reorder_skill_images, name='skill-images-reorder'),
    url(r'^(?P<skill_pk>[0-9]+)/images/upload/$',
        views.ajax_upload_image, name='skill-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_details, name='attribute-details'),
    url(r'attributes/add/$',
        views.attribute_create, name='attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/update/$',
        views.attribute_edit, name='attribute-update'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='attribute-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/add/$',
        views.attribute_value_create,
        name='attribute-value-add'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/update/$',  # noqa
        views.attribute_value_edit,
        name='attribute-value-update'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/delete/$',  # noqa
        views.attribute_value_delete,
        name='attribute-value-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/values/reorder/$',
        views.ajax_reorder_attribute_values,
        name='attribute-values-reorder')]
