version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    restart: unless-stopped
    networks:
      - remote_works-backend-tier
    env_file: common.env
    depends_on:
      - db
      - redis

  db:
    image: library/postgres:11.1-alpine
    restart: unless-stopped
    networks:
      - remote_works-backend-tier
    volumes:
      - remote_works-db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=remote_works
      - POSTGRES_PASSWORD=remote_works

  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    networks:
      - remote_works-backend-tier
    volumes:
      - remote_works-redis:/data

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    command: celery -A remote_works worker --app=remote_works.celeryconf:app --loglevel=info
    restart: unless-stopped
    networks:
      - remote_works-backend-tier
    env_file: common.env
    depends_on:
      - redis

volumes:
  remote_works-db:
    driver: local
  remote_works-redis:
    driver: local

networks:
  remote_works-backend-tier:
    driver: bridge
