version: '2'

services:
  web:
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./remote_works/:/app/remote_works:Z
      - ./templates/:/app/templates:Z
      # prevents overshadowing of build-time assets
      - /app/remote_works/static/assets
      - /app/templates/templated_email/compiled
      # shared volume between celery and web for media
      - remote_works-media:/app/media

  db:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379

  celery:
    volumes:
      - ./remote_works/:/app/remote_works:Z
      - ./templates/:/app/templates:Z
      # prevents overshadowing of build-time assets
      - /app/templates/templated_email/compiled
      # shared volume between celery and web for media
      - remote_works-media:/app/media

volumes:
  saleor-media:
