from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.task_list, name='tasks'),
    url(r'^add/$', views.task_create, name='task-create'),
    url(r'^(?P<task_pk>\d+)/create/$',
        views.create_task_from_draft, name='create-task-from-draft'),
    url(r'^(?P<task_pk>\d+)/$',
        views.task_details, name='task-details'),
    url(r'^(?P<task_pk>\d+)/add-note/$',
        views.task_add_note, name='task-add-note'),
    url(r'^(?P<task_pk>\d+)/cancel/$',
        views.cancel_order, name='task-cancel'),
    url(r'^(?P<task_pk>\d+)/address/(?P<address_type>billing|delivery)/$',
        views.task_address, name='address-edit'),
    url(r'^(?P<task_pk>\d+)/edit-customer/$',
        views.task_customer_edit, name='task-customer-edit'),
    url(r'^(?P<task_pk>\d+)/remove-customer/$',
        views.task_customer_remove, name='task-customer-remove'),
    url(r'^(?P<task_pk>\d+)/edit-delivery/$',
        views.task_delivery_edit, name='task-delivery-edit'),
    url(r'^(?P<task_pk>\d+)/remove-delivery/$',
        views.task_delivery_remove, name='task-delivery-remove'),
    url(r'^(?P<task_pk>\d+)/edit-discount/$',
        views.task_discount_edit, name='task-discount-edit'),
    url(r'^(?P<task_pk>\d+)/edit-voucher/$',
        views.task_voucher_edit, name='task-voucher-edit'),
    url(r'^(?P<task_pk>\d+)/remove-voucher/$',
        views.task_voucher_remove, name='task-voucher-remove'),
    url(r'^(?P<task_pk>\d+)/delete/$',
        views.remove_draft_order, name='draft-task-delete'),

    url(r'^(?P<task_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<task_pk>\d+)/payment/(?P<payment_pk>\d+)/void/$',
        views.void_payment, name='void-payment'),
    url(r'^(?P<task_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<task_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<task_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<task_pk>\d+)/add-variant/$',
        views.add_variant_to_order, name='add-variant-to-task'),
    url(r'^(?P<task_pk>\d+)/fulfill/$',
        views.fulfill_task_lines, name='fulfill-task-lines'),
    url(r'^(?P<task_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/cancel/$',
        views.cancel_fulfillment, name='fulfillment-cancel'),
    url(r'^(?P<task_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/tracking/$',
        views.change_fulfillment_tracking, name='fulfillment-change-tracking'),
    url(r'^(?P<task_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/packing-slips/$',  # noqa
        views.fulfillment_packing_slips, name='fulfillment-packing-slips'),
    url(r'^(?P<task_pk>\d+)/invoice/$',
        views.task_invoice, name='task-invoice'),
    url(r'^(?P<task_pk>\d+)/mark-as-paid/$',
        views.mark_task_as_paid, name='task-mark-as-paid'),

    url(r'^(?P<task_pk>\d+)/ajax/delivery-methods/$',
        views.ajax_task_delivery_methods_list,
        name='ajax-task-delivery-methods')]
