# Generated by Django 2.1.5 on 2019-03-27 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('name',), 'permissions': (('manage_skills', 'Manage Skills.'),)},
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skill.Category'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skillimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='skills'),
        ),
      
    ]
