# Generated by Django 2.1.5 on 2019-03-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_auto_20190327_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='Skill_variant_type',
            new_name='skill_variant_type',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='Skills',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='skillimage',
            old_name='Skill',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='skilltranslation',
            old_name='Skill',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='skillvariant',
            old_name='Skill',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='skillvarianttranslation',
            old_name='Skill_variant',
            new_name='skill_variant',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='Skill_type',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='Skill_type',
        ),
        migrations.AddField(
            model_name='attribute',
            name='skill_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_attributes', to='skill.SkillType'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skill.SkillType'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='skilltranslation',
            unique_together={('language_code', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='skillvarianttranslation',
            unique_together={('language_code', 'skill_variant')},
        ),
    ]
