# Generated by Django 2.1.5 on 2019-04-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_auto_20190327_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillimage',
            name='skill',
        ),
        migrations.AddField(
            model_name='skillimage',
            name='skill_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='skill.SkillType'),
            preserve_default=False,
        ),
    ]
