# Generated by Django 2.1.5 on 2019-06-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_auto_20190409_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltype',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='skillvariant',
            name='weight',
        ),
    ]
