# Generated by Django 2.1.5 on 2019-03-27 18:16

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_slot', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('days_of_week', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='time_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.Schedule'),
        ),
    ]
