# Generated by Django 2.1.5 on 2019-04-07 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190327_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
