# Generated by Django 2.1.5 on 2019-04-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190407_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_slot_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_slot_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
