# Generated by Django 2.1.5 on 2019-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190408_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_slot_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_slot_start',
            field=models.TimeField(null=True),
        ),
    ]
