# Generated by Django 2.1.5 on 2019-04-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190408_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_availability',
        ),
    ]
