# Generated by Django 2.1.5 on 2019-03-25 16:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_prices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('fixed', 'USD'), ('percentage', '%')], default='fixed', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='skill.Category')),
                ('collections', models.ManyToManyField(blank=True, to='skill.Collection')),
                ('skills', models.ManyToManyField(blank=True, to='skill.Skill')),
            ],
            options={
                'permissions': (('manage_discounts', 'Manage sales and vouchers.'),),
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('value', 'All skills'), ('skill', 'Specific skills'), ('collection', 'Specific collections of skills'), ('category', 'Specific categories of skills'), ('delivery', 'Delivery')], default='value', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used', models.PositiveIntegerField(default=0, editable=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('apply_once_per_order', models.BooleanField(default=False)),
                ('discount_value_type', models.CharField(choices=[('fixed', 'USD'), ('percentage', '%')], default='fixed', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('countries', django_countries.fields.CountryField(blank=True, max_length=749, multiple=True)),
                ('min_amount_spent', django_prices.models.MoneyField(blank=True, currency='USD', decimal_places=2, max_digits=12, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='skill.Category')),
                ('collections', models.ManyToManyField(blank=True, to='skill.Collection')),
                ('skills', models.ManyToManyField(blank=True, to='skill.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='discount.Voucher')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vouchertranslation',
            unique_together={('language_code', 'voucher')},
        ),
    ]
